version: "3.8"

services:
  language_tag_tool:
    image: jellyfin-language-tags:latest  # Use the name and tag of your built image
    build:
      context: .  # Build context is the current directory
    environment:
      - INTERVAL_HOURS=3  # Set environment variables here
      - JELLYFIN_URL=https://jellyfin.example.com
      - JELLYFIN_USERNAME=admin
      - JELLYFIN_PASSWORD=example
    restart: unless-stopped  # Automatically restart the container if it stops

  # clear_tags_runner:
  #   image: jellyfin-language-tags:latest
  #   command: clear-tags
  #   environment:
  #     - JELLYFIN_URL=https://jellyfin.example.com
  #     - JELLYFIN_USERNAME=admin
  #     - JELLYFIN_PASSWORD=example
  #   restart: "no"  # Prevent automatic restart for one-off commands
